### ISSUE TITLE
Error when launching app

### ISSUE THREAD

**Issue by oantila** [Andychochocho/android-testing-tool#5]
Getting the following error when launching the app:

Something went wrong: Error: spawn adb ENOENT at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19) at onErrorNT (internal/child_process.js:429:16) at processTicksAndRejections (internal/process/task_queues.js:81:17)

Environment: MacOS 10.14 with ADB installed

Steps to reproduce:
1. Installed build from https://www.dropbox.com/s/enzqotr5bmqtr13/Android%20Test%20Tool.dmg?dl=0
2. Launch app > Note error

<img width="480" alt="Screen Shot 2019-06-17 at 11 31 07 AM" src="https://user-images.githubusercontent.com/2849403/59624215-2c431000-9104-11e9-9866-a16924d39d67.png">

**Comment by oantila** [comment]
Not seeing the error today. Not sure what has changed.

**Comment by oantila** [comment]
Saw this again today. Killing the app and relaunching it made it go away.
